### PR TITLE
Add unselect all and vimdiff when selected files greater than one

### PR DESCRIPTION
**Pull request by shushanxingzhe**

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by pcottle** [comment]
Can we split this out as two different PR's? One just adds that D key and the other changes the vim functionality right?

**Comment by shushanxingzhe** [comment]
Yes of course,Do you mean I split it and commit again or you'll do that

**Comment by pcottle** [comment]
split it up -- i cant split it from my end :) thx for the contributions though!

**Comment by pcottle** [comment]
closing out -- looking forward to the split version!

**Pull request closed without merging**
