### PR TITLE
Bug fix and minor cleanup.

### PR DESCRIPTION
**Pull request by gsheld**
- Fixed bug that manifested as incorrect matches for certain lines in "all-input" mode.

### CODE REVIEW

**Comment by gsheld** [comment]
@pcottle Here's the followup PR as promised. Let me know if you'd like me to update the wiki or the homebrew recipe.

**Comment by pcottle** [comment]
Looks great! Ill try to add some UI tests after this goes in

**Comment by pcottle** [comment]
Boom! now with test coverage too. thanks again @gsheld

**Comment by gsheld** [comment]
@pcottle Glad to help! Good call with the additional test coverage.

**Pull request merged**
