### PR TITLE
use ~/.fpp instead of cluttering up ~

### PR DESCRIPTION
**Pull request by lastquestion**
:wrench:

### CODE REVIEW

**Comment by lastquestion** [comment]
fixes https://github.com/facebook/PathPicker/issues/17

**Comment by pcottle** [comment]
Sweet! I'll resolve the merge conflict and rebase this today, but yeah I think this is the best option compared to using `/tmp` and dealing with multiple user issues.

I might make another module here though that both can import so we dont duplicate these constants anywhere (which was a bad idea to begin with)

**Comment by pcottle** [comment]
Alright we contain everything in `~/.fpp/` now, much cleaner. thanks @lastquestion for the suggested fix and pull request! :tada:

**Comment by lastquestion** [comment]
I think the import module is a good idea but I didn't want to make a big PR. :+1:

**Pull request merged**
