### PR TITLE
Py3 compat

### LINKED ISSUE #4: Python 3.0 compatibility
I'm on 10.10.3. Ran `brew install fpp` and then `fpp`, and got this:

```
File "/usr/local/Cellar/fpp/0.5.3/libexec/src/processInput.py", line 126
    print USAGE_STR
                  ^
SyntaxError: Missing parentheses in call to 'print'
  File "/usr/local/Cellar/fpp/0.5.3/libexec/src/choose.py", line 54
    print 'Nothing to do!'
                         ^
SyntaxError: Missing parentheses in call to 'print'
sh: /Users/dan/.fbPager.sh: No such file or directory
```

### PR DESCRIPTION
**Pull request by zkanda**
Fixes #4

### CODE REVIEW

**Comment by pcottle** [comment]
dont you need to pull in print from future?

```
from __future__ import print
```

dont want to drop 2.6+ support. but then we could support both!
http://python3porting.com/noconv.html

would you like me to add it @zkanda ? or are you ok with the rebsae?

**Comment by zkanda** [comment]
Urgh I got a bit confused with rebasing, but yeah I applied your suggestion. :)

**Comment by pcottle** [comment]
Sweet thanks for the rebase! Im getting one small error still though:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:]$ git diff HEAD~10 | ./fpp
Traceback (most recent call last):
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/processInput.py", line 145, in <module>
    doProgram()
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/processInput.py", line 123, in doProgram
    pickle.dump(lineObjs, open(filePath, 'w'))
TypeError: must be str, not bytes
Traceback (most recent call last):
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/choose.py", line 58, in <module>
    curses.wrapper(doProgram)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/choose.py", line 27, in doProgram
    lineObjs = getLineObjs()
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/choose.py", line 34, in getLineObjs
    lineObjs = pickle.load(open(filePath))
TypeError: 'str' does not support the buffer interface
```

although the tests past just fine with `python3`. it seems to be related to the pickle module -- do you know what differences there might be?

Once we get that solved I can run some more tests and then merge this! would be great to support both python3 and python2

**Comment by pcottle** [comment]
Actually lets merge this for now since it doesnt break 2.6+ support, and pursue the pickle issue in parallel

**Comment by dannguyen** [comment]
Thanks...I had tried my hand at fixing what seems to be pretty easy changes for 3.x compat but couldn't figure out the pickle errors

**Pull request merged**
