### PR TITLE
added test case for describe file feature

### PR DESCRIPTION
**Pull request by rjdean123**
is there a better way to add a change to a PR that was already merged and closed?

anyways, here's a passing test case, let me know if that's not what you were looking for 😄

### CODE REVIEW

**Comment by pcottle** [comment]
its almostttt what we want -- the issue is that since the screen is by default narrow, the sidebar doesnt show, so your command output doesnt show. thats what im trying to get test coverage over

i think you want to add
```
 'screenConfig': {
         'maxX': 201,
         'maxY': 40
     },
```
to your test case. then delete the file and re-run the test and make sure the output file as your command description area

**Comment by rjdean123** [comment]
gah, failing because the 'last accessed' line is different each run, will look more into this when I get some time tomorrow

**Comment by pcottle** [comment]
Oh dangit yeah, that's tricky. That must mean that doing the ls and cat commands on the file ends up recording it as accessed.

If that's the case, is it worth having that line in the output? Its basically always going to be the current day / second if describing the file accesses it, right?

**Comment by rjdean123** [comment]
yeah, that's what i figured--removed the time last accessed feature. luckily i dont think that was one of the more useful features, I think time last modified is more likely to be helpful anyways

**Comment by pcottle** [comment]
```
Traceback (most recent call last):
  File "testScreen.py", line 209, in testScreenInputs
    allInput=('-ai' in args or '--all-input' in args),
  File "/home/travis/build/facebook/PathPicker/src/__tests__/screenTestRunner.py", line 62, in getRowsFromScreenRun
    choose.doProgram(screen, flags, CursesForTest(), lineObjs)
  File "../choose.py", line 42, in doProgram
    screen.control()
  File "../screenControl.py", line 359, in control
    self.processInput(inKey)
  File "../screenControl.py", line 443, in processInput
    self.describeFile()
  File "../screenControl.py", line 349, in describeFile
    self.helperChrome.outputDescription(self.lineMatches[self.hoverIndex])
  File "../screenControl.py", line 77, in outputDescription
    self.outputDescriptionPane(lineObj)
  File "../screenControl.py", line 122, in outputDescriptionPane
    lineObj.getOwnerUser(),
  File "../format.py", line 130, in getOwnerUser
    output = subprocess.check_output(bashCommand.split())
AttributeError: 'module' object has no attribute 'check_output'
----------------------------------------------------------------------
Ran 1 test in 0.912s
FAILED (errors=1)
Tests failed :*(
```

hrm, seems like the tests fail now. mind checking? so close!

**Comment by rjdean123** [comment]
ah, of course haha. weird, they passed locally before I pushed. 

will take a look later today.

**Comment by rjdean123** [comment]
so the expected output file is being generated for a file on my machine, and when it's tested on Travis, the information doesn't line up, which is actually correct behavior. is there a way to generate the expected output on the test server?

But, luckily digging through this issue, I did also realize that a python function i was using was new to python 2.7, and so I was able to rewrite some things to make sure fpp plays nicely with 2.6+/3.0+.

**Comment by pcottle** [comment]
ooooh ugh i know why. its because the files are "new" when they get slurped over to travis and probably have different ownerships or whatever, so the expected values are different

there are two options:

- use dependency injection / mocking to stub out the data returned. thats harder probably
- add a simple `ignoreLines:` parameter to the test config that just ignores comparing the passed in lines:

```
ignoreLines: [45, 49, 51, 53]
```

that way we still execute the code, we just dont care what those specific lines are -- since they will change all the time

sorry about the trouble here! i just want to double check your code is executing and tested -- even if we dont compare the output, getting it executing means if it throws a fatal we will catch that.

and it sounds like it caught the 2.7/3.0 issue already :)

**Comment by rjdean123** [comment]
Got it, yeah, the tests have already proven to be helpful!

taking a look at this now.

**Comment by rjdean123** [comment]
apologies this is taking so long, got quite busy at the end of the summer/start of the new year. should be good to work on this this weekend.

**Comment by pcottle** [comment]
No worries!

**Comment by pcottle** [comment]
closing out since its stale

**Pull request closed without merging**
