### PR TITLE
-i flag only if not in vim shell

### PR DESCRIPTION
**Pull request by alecjacobson**
Hopefully an answer to the problem in https://github.com/facebook/PathPicker/issues/185 (-i flag in shell command causing vim to be suspended).

### CODE REVIEW

**Comment by pcottle** [comment]
Ah sweet! Does this fix #185 for you? Didn't realize we had something like `$VIMRUNTIME`

keep in mind that I think bashrc aliases wont expand in this mode (without the `-i` option) but I would need to check. thats better than hanging the shell though.

**Comment by pcottle** [comment]
Another thought -- should we prevent going into editor mode if we are already inside a vim runtime when we launch `fpp`? I dont think theres a valid case for running vim as launched from a vim bash command

**Comment by alecjacobson** [comment]
I agree it's better than hanging the shell. It's also possible to load
.bashrc etc. explicitly using the source command.

Personally, I actually _do_ like the ability to launch the editor from vim
mode. This matches the behavior of issue `:vim filename` within vim: a new
vim process is run, quitting that one will pop up to the original one.

**Comment by pcottle** [comment]
Lets do it! Thanks for putting up the fix -- this will make the next release, but in the meantime you can tell your friends to install from HEAD on master (since you already have the fix locally)

**Pull request merged**
