### PR TITLE
Fix $whereami and other bash linting for Issue #6

### PR DESCRIPTION
**Pull request by n06**
Fixes an issue where the path of the shell script is added on twice. (Eg. <path>/<path>/fpp). Also fixed some variable scoping in the script just for niceness.

### CODE REVIEW

**Comment by pcottle** [comment]
definitely down for this line:
`+BASEDIR=$(cd "$BASEDIR" && pwd)`

however i remember having to append the slashes since the `brew` installation has multiple hops. Let me get some command line output

**Comment by pcottle** [comment]
```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ git diff HEAD~10 --stat | fpp
WHEREAMI is /usr/local/bin/../Cellar/fpp/0.5.3/bin/fpp
WHEREAMI is /usr/local/bin/../Cellar/fpp/0.5.3/bin/../libexec/fpp
nothing to do!
```

Yeah, see the tricky thing is that `homebrew` installs **relative** symbolic links, so switching to your first change unfortunately breaks:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ git diff HEAD~10 --stat | fpp
WHEREAMI is ../Cellar/fpp/0.5.3/bin/fpp
/usr/local/bin/fpp: line 19: cd: ../Cellar/fpp/0.5.3/bin: No such file or directory
python: can't open file '/src/processInput.py': [Errno 2] No such file or directory
python: can't open file '/src/choose.py': [Errno 2] No such file or directory
nothing to do!
```

**Comment by pcottle** [comment]
Do you mind updating with just the `BASEDIR=$(cd "$BASEDIR" && pwd)` change? ill happily accept that! that was just my shortsightedness / bash inexperience

**Comment by n06** [comment]
Ah I see, the perils of being on linux and not OS X. I'll change this to just include the scoping for now, and see if I can come up with something else for the path issues later

**Comment by pcottle** [comment]
@n06 I actually think this got solved in #16 since we have better symbolic link resolution everywhere. do you mind checking if that works for you? closing out in the meantime since this is on a stale rev

**Pull request closed without merging**
