### PR TITLE
Created a script for automatic creation of .deb packages from source Resolve #43

### LINKED ISSUE #43: Linux packages
It would be good to have Linux packages available, at least .deb and .rpm versions. I don't know anyone that uses Linuxbrew, it doesn't seem ideal on Linux when better solutions exist.

The HHVM team distribute Linux packages, you could probably see how they do it.

### PR DESCRIPTION
**Pull request by pallavagarwal07**
As mentioned by @pcottle , I have made the necessary additions to makeDist.py and created all necessary files in debian directory which would facilitate the creation of the debian package.
Please review.

I have already accepted Facebook's Contributor License Agreement (CLA).

### CODE REVIEW

**Comment by pcottle** [comment]
:clap: :heart_eyes: this is awesome @pallavagarwal07. Did you see my comment about the man pages? we could use the output of `fpp --help` to generate that, since it will show all the possible command line options and the most recent usage strings.

Im installing `dpkg` via brew so hopefully I can run this myself as well. most of this is magic to me but im excited to try it out

**Comment by pallavagarwal07** [comment]
@pcottle Yes, I saw the comment. The format of the man pages is usually fixed. I don't think the same page can be used. I'll have to read up a bit more before I can say for sure.

**Comment by pcottle** [comment]
hrm im getting one error:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:]$ dpkg --build ./
dpkg-deb: error: parsing file './/DEBIAN/control' near line 7:
 missing package name
```

so i cant try it out. curious what you think about the man page but if we dont go that direction ill merge this PR just so we have somewhere to start for the linux packages

**Comment by pallavagarwal07** [comment]
Try this:
install devscripts package, comment out lines from 3-12 in makeDist.py and run ./scripts/makeDist.py from the source directory (in which scripts, debian) folders are present

I have used debuild command to create packages. It runs both dpkg and some verify script internally. But this works perfectly on mine. Will try directly by dpkg and report back

**Comment by pallavagarwal07** [comment]
Yeah. Getting the same errors when running dpkg manually

**Comment by pallavagarwal07** [comment]
The more I am trying dpkg, the more I'm convinced that the method I followed was debhelper specific. Run using the script in makeDist. It also rewrites one of the file to have the correct version number and timestamp. So package won't be build directly anyway.

**Comment by pallavagarwal07** [comment]
@pcottle
Is there a chance I could talk to you (on chat / skype)? I think I can fix the problem but I have some doubts like about where the script would be run etc.

**Comment by pallavagarwal07** [comment]
@pcottle 
I have rewritten the files on basis of dpkg. Now executing package.sh inside the debian directory creates the .deb file in the parent without any problems.

Note: file should be executed from inside the debian directory, fakeroot should be installed.

Please review

**Comment by tpalsulich** [comment]
Works for me on Ubuntu 15.04:

```
➜  PathPicker git:(DebianPackaging) cd debian 
➜  debian git:(DebianPackaging) ✗ fpp --help
zsh: command not found: fpp
➜  debian git:(DebianPackaging) ./package.sh 
dpkg-deb: building package `pathpicker' in `../fpp.deb'.
➜  debian git:(DebianPackaging) ✗ sudo dpkg -i ../fpp.deb
Selecting previously unselected package pathpicker.
(Reading database ... 216159 files and directories currently installed.)
Preparing to unpack ../fpp.deb ...
Unpacking pathpicker (0.5.7) ...
Setting up pathpicker (0.5.7) ...
➜  debian git:(DebianPackaging) ✗ sudo apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
➜  debian git:(DebianPackaging) ✗ fpp --help
********************************************************************************

Welcome to fpp, the Facebook PathPicker! We hope your stay
...
➜  debian git:(DebianPackaging) ✗ sudo apt-get remove pathpicker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  pathpicker
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 214 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 216214 files and directories currently installed.)
Removing pathpicker (0.5.7) ...
➜  debian git:(DebianPackaging) ✗ fpp --help
zsh: command not found: fpp
```

**Comment by pallavagarwal07** [comment]
@pcottle 
Did you check this yet? **The script only uses fakeroot, sed, and dpkg now**. They should all work fine on Mac.

**Comment by pcottle** [comment]
Thanks @tpalsulich for the check. I'm trying this out right now and I think a few things are broken if there's a space in the name:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker/debian:]$ ./package.sh 
/usr/bin/python: can't find '__main__' module in '/Users/pcottle/Dropbox'
mkdir: /Users/pcottle/Dropbox: File exists
```

Which is yet again a reason why Dropbox shouldn't have introduced spaces in their enterprise product :angry: :rage: but I digress...

let me try to patch in some quotes and fix this up

**Comment by tpalsulich** [comment]
I'm mobile right now. But, from what I remember, you'll need some quotes around {}.

**Comment by pcottle** [comment]
```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker/debian:]$ ln --symbolic
ln: illegal option -- -
```

My `ln` doesnt have the `--symbolic` option, only `-s` so ill change this too

**Comment by pcottle** [comment]
There we go, finally got it to work and made the script much more idempotent:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker/debian:]$ ./package.sh 
Building fpp version 0.5.7 at Wed, 20 May 2015 09:05:14 -0700
====================
Control file is:
====================
Package: pathpicker
Version: 0.5.7
Architecture: all
Maintainer: Peter Cottle <pcottle@fb.com>
Installed-Size: 209
Section: misc
Priority: optional
Description: Bash Output File Picker
 PathPicker parses piped input for files and presents it in a convenient UI.
====================
Creating symlink...
====================
Changelog is:
====================
pathpicker (0.5.7) UNRELEASED; urgency=low

  * Release version 0.5.7.

 -- Peter Cottle <pcottle@fb.comn>  Wed, 20 May 2015 09:04:29 -0700
====================
Gziping...
/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/debian/usr/share/doc/pathpicker/changelog.gz already exists -- do you wish to overwrite (y or n)? y
Setting permissions...
find: -exec: no terminating ";" or "+"
Building package...
dpkg-deb: building package `pathpicker' in `../fpp.deb'.
usage: chown [-fhv] [-R [-H | -L | -P]] owner[:group] file ...
       chown [-fhv] [-R [-H | -L | -P]] :group file ...
Done! Check out ../fpp.deb
```

@pallavagarwal07 something to consider also is that since `usr/share/doc/pathpicker/changelog` is tracked by version control, you cant just delete it since then we will have local changes to the directory. so ill add some stuff to fix that

**Comment by pcottle** [comment]
Ahhh now its so clean :heart_eyes: 

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker/debian:master]$ ./package.sh 
Building fpp version 0.5.7 at Wed, 20 May 2015 09:11:12 -0700
====================
Control file is:
====================
Package: pathpicker
Version: 0.5.7
Architecture: all
Maintainer: Peter Cottle <pcottle@fb.com>
Installed-Size: 209
Section: misc
Priority: optional
Description: Bash Output File Picker
 PathPicker parses piped input for files and presents it in a convenient UI.
====================
Creating symlink...
====================
Changelog is:
====================
pathpicker (0.5.7) UNRELEASED; urgency=low

  * Release version 0.5.7.

 -- Peter Cottle <pcottle@fb.comn>  Wed, 20 May 2015 09:11:12 -0700
====================
Gziping...
Setting permissions...
find: -exec: no terminating ";" or "+"
Building package...
dpkg-deb: building package `pathpicker' in `../fpp.deb'.
usage: chown [-fhv] [-R [-H | -L | -P]] owner[:group] file ...
       chown [-fhv] [-R [-H | -L | -P]] :group file ...
Restoring template files...
/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/debian/usr/bin
Done! Check out fpp.deb
[pcottle:~/Dropbox (Facebook)/wip/PathPicker/debian:master]$ gs
## master...origin/master
```

One thing is that logspew from the packager:

```
dpkg-deb: building package `pathpicker' in `../fpp.deb'.
usage: chown [-fhv] [-R [-H | -L | -P]] owner[:group] file ...
       chown [-fhv] [-R [-H | -L | -P]] :group file ...
```

thats ok right?

**Comment by pallavagarwal07** [comment]
Thanks, I'll keep that in mind. Should I do the rpm packages next?

**Comment by pcottle** [comment]
Thanks a bunch @pallavagarwal07 I definitely couldn't have done this on my own. Now that we have debian packages, I assume just including them with the next release so they can be downloaded is sufficient right? Is there any easy command we should list in the README for installation?

**Comment by pallavagarwal07** [comment]
Seems fine, although I would be more relieved if I tested the deb built on your system by installing it on mine

**Comment by pallavagarwal07** [comment]
Installation usually is done by double clicking. On worst cases it can be installed by dpkg - i command.  Although I haven't met a debian system where double clicking the downloaded file didn't work

**Comment by pcottle** [comment]
@pallavagarwal07 here's a link!
https://dl.dropboxusercontent.com/u/15917930/fpp.deb

**Comment by pallavagarwal07** [comment]
Seems to install and work fine :smile: But Lintian is giving some errors. Lintian checks for .deb packages for best practices. The deb produced on my system isn't giving any :frowning:

**Comment by pallavagarwal07** [comment]
Anyway, those are only warnings. Shouldn't cause any trouble.

**Comment by pcottle** [comment]
Alright great! I'll be sure to include the debian package in the next release and update the README with the link

**Comment by pcottle** [comment]
Oh wait you can edit releases, let me put this up now...

**Comment by pallavagarwal07** [comment]
Awesome! 
Let me know if I should write a man page for this. Debian packages are usually expected to have one.

**Comment by pcottle** [comment]
Alright readme updated!
https://github.com/facebook/PathPicker#linux

**Comment by pcottle** [comment]
If you feel particularly compelled @pallavagarwal07 go ahead! But I'm not sure how "bad" it is to not have a manpage -- if its not a huge deal then maybe its not worth your time. However if its a huge debian "faux pa" then maybe we should

**Comment by pallavagarwal07** [comment]
Please break up the Linux section into parts. AUR is for Arch ONLY.
.deb package is only for debian systems. 
.rpm, which should be the next ToDo, would be for RedHat Linux derivatives

**Comment by pcottle** [comment]
@pallavagarwal07 mind sending a PR for the README? you know what you're talking about haha

**Comment by pallavagarwal07** [comment]
Will do.

**Pull request merged**
