### PR TITLE
Compress release tar file (tgz)

### PR DESCRIPTION
**Pull request by gliptak**
https://github.com/facebook/PathPicker/issues/174

### CODE REVIEW

**Comment by pcottle** [comment]
This is all greek to me; I trust the contributor community knows more than me :) thanks for the PR!

**Comment by pcottle** [comment]
(next time we have a release this will be reflected)

**Comment by gliptak** [comment]
@pcottle Peter, could you run the script on your Mac to validate that the ```z``` flag is there with ```tar```. If it isn't I will submit a slightly updated PR.

**Comment by pcottle** [comment]
`[pcottle:~/Desktop:]$ tar -czf crisis_launches.xlsx ./practice/` worked!

**Comment by pcottle** [comment]
whoops i overwrote my excel file lol. but it still works

**Comment by gliptak** [comment]
Thanks :)

**Pull request merged**
