### PR TITLE
Use bold/bright white for hovered and selected text

### PR DESCRIPTION
**Pull request by ptzz**
Related to #236.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by pcottle** [comment]
Alright cool we can boldify these colors as well!

However if you look at:
https://github.com/facebook/PathPicker/commit/2c6e55a3f40c8d3e540af7184d57033b387600aa

I had to add an expected mapping for that new color attribute for the screen tests, and then regen a lot of the tests since their output has "changed" to some degree. its a bit of a pain so I'll go ahead and do it for you, but let me know if you want to get added as a contributor with some other change

**Comment by ptzz** [comment]
Yeah I noticed the tests failing and that it seemed non-trivial to fix. Thanks for integrating!

**Pull request closed without merging**
